# Generated by Django 5.2.8 on 2025-11-22 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_product_created_at_remove_product_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(choices=[('Warehouse', 'Warehouse'), ('Rack A', 'Rack A'), ('Rack B', 'Rack B'), ('Rack C', 'Rack C')], max_length=100)),
                ('to_location', models.CharField(choices=[('Warehouse', 'Warehouse'), ('Rack A', 'Rack A'), ('Rack B', 'Rack B'), ('Rack C', 'Rack C')], max_length=100)),
                ('quantity', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
