# Generated by Django 5.2.8 on 2025-11-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaltransfer',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
