# Generated by Django 5.2.8 on 2025-11-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_movementhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementhistory',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='movementhistory',
            name='source',
        ),
        migrations.AddField(
            model_name='movementhistory',
            name='from_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movementhistory',
            name='new_stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movementhistory',
            name='previous_stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movementhistory',
            name='to_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movementhistory',
            name='movement_type',
            field=models.CharField(choices=[('Receipt', 'Receipt'), ('Delivery', 'Delivery'), ('Adjustment', 'Adjustment'), ('Transfer-Out', 'Transfer-Out'), ('Transfer-In', 'Transfer-In')], max_length=20),
        ),
    ]
